<a href="https://colab.research.google.com/github/vaal129/Arreglos_12_08_2025/blob/main/vectores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #np es un alias para recortar el nombre de numpy

vector = np.array([1, 2, 3, 4, 5])
print(vector)

print (vector[2])

"""Los vectores o son como las listas, no tiene  un metodo end() para agregar elementos o tienen un metodo pop() para eliminar elementos, pero si tenen metodo reshape()
 para cambiar su forma, adicionalmente despues creado no se puede cambiar el tamaño del vector. """

vector1  = np.zeros(5)
print(vector1)

vector2 = np.ones(5)
print(vector2)

vector3 = np.arange(1,10)
print("rango", vector3)

vector4 = np.linspace(1,10,5)
print("linspace", vector4)

vector5 = np.random.rand(10)
print("random", vector5)

vector6 = np.random.randint(1,10,100)
print("random int", vector6)

[1 2 3 4 5]
3
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
rango [1 2 3 4 5 6 7 8 9]
linspace [ 1.    3.25  5.5   7.75 10.  ]
random [0.70294086 0.8934985  0.33596643 0.04982908 0.08448442 0.30475149
 0.25739024 0.68132012 0.75104067 0.05858329]
random int [8 4 1 6 6 6 4 1 3 5 3 5 3 4 6 1 9 1 1 7 3 1 3 8 5 9 7 2 3 1 4 9 5 1 5 9 3
 5 9 3 8 5 1 7 7 7 3 2 7 7 1 8 6 1 8 5 6 7 1 8 4 7 9 3 8 8 2 9 6 8 8 5 3 3
 9 7 3 6 8 3 9 6 8 5 8 1 8 8 5 7 1 4 3 3 8 8 6 1 3 5]


In [2]:
import numpy as np

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

suma= vector1 + vector2
print("\033[31mSuma de vectores:", suma, "\033[0m")

resta = vector1 - vector2
print("\033[33mResta de vectores:", resta, "\033[0m")

producto = vector1 * vector2
print("\033[32mProducto de vectores:", producto, "\033[0m")

division = vector1 / vector2
print("\033[36mDivision de vectores:", division, "\033[0m")

potencia = vector1 ** 2
print("\033[35mPotencia de vectores:", potencia, "\033[0m")

Suma de vectores: [5 7 9] 
Resta de vectores: [-3 -3 -3] 
Producto de vectores: [ 4 10 18] 
Division de vectores: [0.25 0.4  0.5 ] 
Potencia de vectores: [1 4 9] 
